version: "2.2"
services:
  f1bot:
    build:
      context: .
      dockerfile: docker/f1bot.dockerfile
    env_file:
      - .env
    container_name: f1bot
    command: ["python", "-u", "main.py"]
    restart: unless-stopped
